# Generated by Django 4.2.29 on 2026-03-31 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('db', '0121_alter_estimate_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FundingOpportunity',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('external_id', models.CharField(help_text='Original ID from the funding cockpit, e.g. CASCADE-001', max_length=64)),
                ('opportunity_type', models.CharField(blank=True, default='', help_text='Cascade, Horizon, MSCA, etc.', max_length=64)),
                ('budget', models.CharField(blank=True, default='', max_length=128)),
                ('relevance', models.IntegerField(default=1, help_text='1-5 relevance score')),
                ('fit_notes', models.TextField(blank=True, default='')),
                ('source', models.CharField(blank=True, default='', max_length=256)),
                ('url', models.URLField(blank=True, default='', max_length=512)),
                ('call_id', models.CharField(blank=True, default='', max_length=128)),
                ('next_step', models.TextField(blank=True, default='')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funding_meta', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Funding Opportunity',
                'verbose_name_plural': 'Funding Opportunities',
                'db_table': 'funding_opportunities',
            },
        ),
        migrations.CreateModel(
            name='FundingActivityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('field', models.CharField(max_length=64)),
                ('old_value', models.TextField(blank=True, default='')),
                ('new_value', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='funding.fundingopportunity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Funding Activity Log',
                'verbose_name_plural': 'Funding Activity Logs',
                'db_table': 'funding_activity_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
