# Generated by Django 4.2.29 on 2026-03-31 23:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('db', '0121_alter_estimate_type'),
        ('funding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingopportunity',
            name='linked_docs',
            field=models.JSONField(blank=True, default=list, help_text='List of KB file paths linked to this opportunity'),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Opportunity tags'),
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=512)),
                ('version', models.CharField(default='v1', max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('internal_review', 'Internal Review'), ('submitted', 'Submitted'), ('revision_requested', 'Revision Requested'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='draft', max_length=32)),
                ('submission_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='funding.fundingopportunity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Proposal',
                'verbose_name_plural': 'Proposals',
                'db_table': 'funding_proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=256)),
                ('organization_type', models.CharField(blank=True, default='', help_text='SME, University, Research Institute, Large Enterprise, NGO, Public Body', max_length=64)),
                ('country', models.CharField(blank=True, default='', max_length=64)),
                ('contact_name', models.CharField(blank=True, default='', max_length=256)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254)),
                ('expertise', models.TextField(blank=True, default='')),
                ('website', models.URLField(blank=True, default='', max_length=512)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funding_partners', to='db.workspace')),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
                'db_table': 'funding_partners',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('date', models.DateTimeField()),
                ('attendees', models.TextField(blank=True, default='', help_text='Comma-separated names or emails')),
                ('notes', models.TextField(blank=True, default='')),
                ('action_items', models.TextField(blank=True, default='')),
                ('meeting_type', models.CharField(choices=[('internal', 'Internal'), ('partner', 'Partner Call'), ('info_day', 'Info Day'), ('review', 'Review Meeting'), ('kickoff', 'Kickoff'), ('progress', 'Progress Meeting')], default='internal', max_length=32)),
                ('location', models.CharField(blank=True, default='', max_length=256)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='funding.fundingopportunity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'db_table': 'funding_meetings',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ImplementationMilestone',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='pending', max_length=32)),
                ('deliverable', models.CharField(blank=True, default='', max_length=256)),
                ('notes', models.TextField(blank=True, default='')),
                ('budget_spent', models.CharField(blank=True, default='', max_length=64)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='funding.fundingopportunity')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Implementation Milestone',
                'verbose_name_plural': 'Implementation Milestones',
                'db_table': 'funding_milestones',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='ConsortiumMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('role', models.CharField(choices=[('coordinator', 'Coordinator'), ('partner', 'Partner'), ('subcontractor', 'Subcontractor'), ('associated', 'Associated Partner')], default='partner', max_length=64)),
                ('work_package', models.CharField(blank=True, default='', max_length=128)),
                ('budget_share', models.CharField(blank=True, default='', max_length=64)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consortium_members', to='funding.fundingopportunity')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consortium_memberships', to='funding.partner')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Consortium Member',
                'verbose_name_plural': 'Consortium Members',
                'db_table': 'funding_consortium_members',
                'ordering': ['role', 'partner__name'],
            },
        ),
    ]
